src/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, mail_user, domain
from flask_login import login_user, login_required, logout_user, current_user
from flask_mail import Mail, Message
import os
import random
import string

# load blueprint and mail for auth.py
auth = Blueprint('auth', __name__)
mail = Mail()

# this route handle user/admin login
@auth.route('/login', methods=['GET', 'POST'])
def login():
    # fetch user submitted data
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        # check if user is exist or not
        user = User.query.filter_by(email=email).first()
        if user:
    # if user is exist then check password is match or not
            if check_password_hash(user.password, password):
    # if user password is match then set user login session
                login_user(user, remember=True)
    # if all above things is true then check is this user is 1:admin or 0:user
                if user.role == 0:
                    return redirect(url_for('views.home'))
                elif user.role == 1:
                    return redirect(url_for('views.admin_dashboard'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)

# this route will logout user & admin also destroy login session
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

# this route for sign up new user
@auth.route('/sign_up', methods=['GET', 'POST'])
def sign_up():
    # fetching user submitted data
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('fname')
        last_name = request.form.get('lname')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        # check if email is already exist or not
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        # check if email length. it shoulb be at least 13 characters
        elif len(email) < 13:
            flash('Email must be greater than 3 characters.', category='error')
        # check length of first name
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        # check length of last name
        elif len(last_name) < 2:
            flash('Last name must be greater than 1 character.', category='error')
        # check if password & confirm password is match or not
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        # check if password length is at least grater than 8 characters
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        # if everything is true all above, then add new user into database and redirect to login page
        else:
            new_user = User(email=email, fname=first_name, lname=last_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account has been created successfully. Please login to continue...', category='success')
            return redirect(url_for('auth.login'))

    return render_template("sign_up.html", user=current_user)

# this route for forgot password page
@auth.route("/reset_password", methods=["GET", "POST"])
def reset_password():
    if request.method == "GET":
        return render_template("forgot_pass.html", user=current_user)
    # fetch user submitted data
    if request.method == "POST":
        email = request.form.get("email")
        # check: is this user exist in database
        fetch_user = User.query.filter_by(email=email).first()
        if fetch_user:
            """ if user is exist then generate a random string for create reset password url and save it into database """
            hashCode = ''.join(random.choices(string.ascii_letters + string.digits, k=75))
            fetch_user.hashCode = hashCode
            db.session.commit()
            """ after complete all above then send a password reset email to user provided email address """
            msg = Message('Your password reset link', sender=mail_user, recipients=[email])
            msg.body = f"Hello {fetch_user.fname},\nWe've received a request to reset your password. Click the link bellow and set a new password.\nlink: {domain}/password_reset_confirmation_url/{fetch_user.hashCode}"
            mail.send(msg)
            flash("We've sent a password reset link to your email", category="success")
            return redirect(url_for("auth.reset_password"))
        else:
            flash("User not exists!", category="error")
            return redirect(url_for("auth.reset_password"))

# this route handle: when user click password reset url from sent email
@auth.route("/password_reset_confirmation_url/<string:hashCode>")
def password_reset_confirmation_url(hashCode):
    # fetch hash code from database that was created before
    fetch_hash = User.query.filter_by(hashCode=hashCode).first()
    if fetch_hash:
        # if hash code is matched then show/render add new password form
        return render_template("set_new_pass.html", user_id=fetch_hash.id, user=current_user)
    else:
        flash("Password reset link has been expired", category="error")
        return redirect(url_for("auth.login"))

# this handler route save new password
@auth.route("/set_new_pass", methods=["GET", "POST"])
def set_new_pass():
    if request.method == "POST":
        password = request.form.get("password")
        user_id = request.form.get("user_id")
        User.query.filter_by(id=user_id).update(dict(password=generate_password_hash(password, method="sha256"), hashCode=0))
        db.session.commit()
        # if password has changed then redirect to login page
        flash("Your password has been changed successfully", category="success")
        return redirect(url_for('auth.login'))

# this route for handle changing user password from user profile page
@auth.route("/change_password", methods=["GET", "POST"])
@login_required
def change_password():
    # render/show change password form page
    if request.method == "GET":
        return render_template("user/change_password.html", user=current_user)
    # fetch user submitted data
    if request.method == "POST":
        old_pass = request.form.get("old_pass")
        new_pass = request.form.get("new_pass")
        re_pass = request.form.get("re_pass")
    # check: if new password & confirm password is match or not
        if new_pass == re_pass:
            # check: if old password is match with user submitted old_pass
            if check_password_hash(current_user.password, old_pass):
                gen_hash_pass = generate_password_hash(new_pass, method="sha256")
                User.query.filter_by(id=current_user.id).update(dict(password=gen_hash_pass))
            # if all above is true then put new password into database & save changes
                db.session.commit()
                flash("Your password has been changed successfully", category='success')
                return redirect(url_for('auth.change_password'))
            # redirect if old password doesn't match with database
            else:
                flash("Old password doesn't match!", category='error')
                return redirect(url_for('auth.change_password'))
        # redirect if old password doesn't match with new password
        else:
            flash("Couldn't match New password and Confirm password!", category='error')
            return redirect(url_for('auth.change_password'))

# this route handle user account deletion from user profile page
@auth.route("/user_account_delete", methods=["POST"])
@login_required
def user_account_delete():
    password = request.form.get("password")
    if check_password_hash(current_user.password, password):
        fetch_user = User.query.filter_by(id=current_user.id).first()
        os.remove(f"src/static/img/user_avatars/{fetch_user.avatar}")
        db.session.delete(fetch_user)
        db.session.commit()
        flash("Account has been deleted permanently", category="success")
        return redirect(url_for('auth.login'))
    else:
        flash("Invalid password! please try again...", category="error")
        return redirect(url_for('views.user_dashboard'))

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>{% block title %}{% endblock title %}</title>
<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='css/materialUI.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='css/tiny-slider.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>
<body class="intro-page transport-lp">

{% block content %}
{% endblock content %}

<footer class="page-footer mdb-color darken-3 text-center text-md-left pt-5">

    <!--Footer Links-->
    <div class="container mb-3">

      <!--First row-->
      <div class="row">

        <!--First column-->
        <div class="col-md-4 mt-1 mb-1 wow fadeIn" data-wow-delay="0.3s">
          <!--About-->
          <h5 class="title mb-4 font-weight-bold">ABOUT COMPANY</h5>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam quibusdam eum odit impedit ipsum odio, ipsa dolore, nihil distinctio voluptate repellat, suscipit! Autem, incidunt debitis.</p>

          <div class="footer-socials mt-2">

            <!--Facebook-->
            <a type="button" class="btn-floating  btn-primary"><i class="fab fa-facebook-f"></i></a>
            <!--Dribbble-->
            <a type="button" class="btn-floating  btn-danger-2"><i class="fab fa-dribbble"></i></a>
            <!--Twitter-->
            <a type="button" class="btn-floating  btn-cyan"><i class="fab fa-twitter"></i></a>
            <!--Google +-->
            <a type="button" class="btn-floating  btn-danger"><i class="fab fa-google-plus-g"></i></a>

          </div>
        </div>
        <!--/First column-->

        <hr class="w-100 clearfix d-md-none">

        <!--Second column-->
        <div class="col-lg-3 ml-lg-auto col-md-4 mt-1 mb-1 wow fadeIn" data-wow-delay="0.3s">
          <!--Search-->
          <h5 class="text-uppercase mb-4 font-weight-bold">Pages</h5>
          <p class="mb-1"><a href="{{ url_for('views.home') }}">Home</a></p>
          <p class="mb-1"><a href="{{ url_for('views.rooms') }}">Rooms</a></p>
          <p class="mb-1"><a href="{{ url_for('views.contact') }}">Contact</a></p>
          <p class="mb-1"><a href="{{ url_for('views.user_dashboard') }}">Accounts</a></p>

        </div>
        <!--/Second column-->

        <hr class="w-100 clearfix d-md-none">

        <!--Third column-->
        <div class="col-lg-3 ml-lg-auto col-md-4 mt-1 mb-1 wow fadeIn" data-wow-delay="0.3s">
          <!--Contact-->
          <h5 class="text-uppercase mb-4 font-weight-bold text-center" id="footer_form_title">Get in Touch</h5>
          <p class="mb-4 text-center" id="footer_form_res"></p>
          <form id="footer_form">
            <input type="text" id="full_name" name="full_name" class="form-control mb-2" id="email" name="email" placeholder="Full name" required>
            <input type="email" id="email" name="email" class="form-control mb-2" placeholder="Email" required>
                <select name="subject" id="subject" class="browser-default custom-select mb-2" required>
                    <option disabled selected>Subject</option>
                    <option value="Feedback">Feedback</option>
                    <option value="Request for a room">Request for room</option>
                    <option value="Other">Other</option>
                </select>
              <div class="form-group">
                    <textarea class="form-control rounded-0" id="message" name="message" rows="3" placeholder="Message" required></textarea>
              </div>
              <button type="submit" id="footer_form_btn" class="btn btn-primary btn-block">Send</button>
          </form>

        </div>
        <!--/Third column-->

      </div>
      <!--/First row-->

    </div>
    <!--/Footer Links-->
<hr style="background: #757575; margin: 0;">
    <!--Copyright-->
    <div class="footer-copyright py-3 text-center">
      <div class="container-fluid text-light">&copy; <span id="current_year"></span> Bed & Breakfast <i class="fas fa-utensils"></i> | All Rights Reserved</div>
    </div>
    <!--/Copyright-->

</footer>
<!--/Footer-->
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/materialUI.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/tiny-slider.js') }}"></script>
<script src="https://js.stripe.com/v3/"></script>
<script>
new WOW().init();
var slider = tns({
    container: '.home_room_slider',
    items: 1,
    controls: false,
    slideBy: "page",
    mouseDrag: true,
    loop: true,
    rewind: true,
    autoplay: true,
    autoplayButtonOutput: false,
    autoplayTimeout: 3000,
    navPosition: "bottom",
    speed: 400,
    gutter: 15,
    responsive: {
        767: {
            items: 3
        },
    },
});
</script>
<script>
$(document).ready(function(){
$("#current_year").html(new Date().getFullYear());
$("#res_div").hide();
$("#contact_form").on("submit", function(e){
    e.preventDefault();
    $("#submit_btn").html("Sending <img src="+ "{{ url_for('static', filename='img/loader.gif') }}" +" style='width: 20px;'>");
    $("#submit_btn").attr("disabled", true);
    $.ajax({
        url: "{{ url_for('views.contact') }}",
        type: "POST",
        data: $(this).serialize(),
        success: function(data){
            $("#res_msg").html(data);
            $("#contact_form").hide();
            $("#res_div").show();
        }
    });
});
});
</script>
<script>
$(document).ready(function(){
$("#footer_form_res").hide();
$("#footer_form").on("submit", function(e){
    e.preventDefault();
    $("#footer_form_btn").html("Sending <img src="+ "{{ url_for('static', filename='img/loader.gif') }}" +" style='width: 20px;'>");
    $("#footer_form_btn").attr("disabled", true);
    $.ajax({
        url: "{{ url_for('views.home') }}",
        type: "POST",
        data: $(this).serialize(),
        success: function(data){
            $("#footer_form_res").html(data);
            $("#footer_form_title").hide();
            $("#footer_form_res").show();
            $("#footer_form")[0].reset();
            $("#footer_form_btn").html("Send");
            $("#footer_form_btn").attr("disabled", false);
        }
    });
});
});
</script>
<script>
$(document).ready(function(){
  $("#password, #password2").keyup(validate);
  $("#set_new_pass_btn").attr("disabled", true);

function validate() {
  var password = $("#password").val();
  var password2 = $("#password2").val();
 
    if(password == password2){
       $("#match_res").html("<span class='text-success'>Password matched</span>");
       $("#set_new_pass_btn").attr("disabled", false);
    }
    else{
        $("#match_res").html("<span class='text-danger'>Confirm password didn't match!</span>");
        $("#set_new_pass_btn").attr("disabled", true);
    }
}
});
</script>
{% block script %}{% endblock script %}
</body>
</html>

src/templates/contact.html
{% extends "base.html" %}
{% block title %}B&B{% endblock title %}
{% include "navbar.html" %}
{% block content %}

<div class="container mb-4 py-5 z-depth-1" style="margin-top: 90px;">
  <!--Section: Content-->
  <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">

    <!--Google map-->
    <div id="map-container-google-1" class="z-depth-1 map-container mb-5">
      <iframe src="https://maps.google.com/maps?q=53.349804, -6.260310&z=15&output=embed" frameborder="0" allowfullscreen>
	</iframe>
    </div>
    <!--Google Maps-->

    <!--Grid row-->
    <div class="row">

      <!--Grid column-->
      <div class="col-lg-5 col-md-12 mb-0 mb-md-0">

        <h3 class="font-weight-bold">Contact Us</h3>

        <p class="text-muted">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id quam sapiente
          molestiae
          numquam quas, voluptates omnis nulla ea odio quia similique corrupti magnam, doloremque laborum.</p>

        <p><span class="font-weight-bold mr-2">Email:</span><a href="">contact@mycompany.com</a></p>
        <p><span class="font-weight-bold mr-2">Phone:</span><a href="">+353 123 456 789</a></p>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-7 col-md-12 mb-4 mb-md-0">
<div id="res_div" class="text-center">
<p id="res_msg" class="text-center text-success"></p>
<img src="{{ url_for('static', filename='img/mail_response.gif') }}" style="width: 470px;">
</div>
<form id="contact_form">
        <!--Grid row-->
        <div class="row">

          <!--Grid column-->
          <div class="col-md-6">

            <!-- Material outline input -->
            <div class="md-form md-outline mb-0">
              <input type="text" id="fname" name="fname" class="form-control" required>
              <label for="form-first-name">First name</label>
            </div>

          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-6">

            <!-- Material outline input -->
            <div class="md-form md-outline mb-0">
              <input type="text" id="lname" name="lname" class="form-control" required>
              <label for="form-last-name">Last name</label>
            </div>

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

        <!-- Material outline input -->
        <div class="md-form md-outline mt-3">
          <input type="email" id="email" name="email" class="form-control" required>
          <label for="form-email">Email</label>
        </div>

        <!-- Material outline input -->
        <div class="md-form md-outline">
          <input type="text" id="subject" name="subject" class="form-control" required>
          <label for="form-subject">Subject</label>
        </div>

        <!--Material textarea-->
        <div class="md-form md-outline mb-3">
          <textarea id="message" name="message" class="md-textarea form-control" rows="3" required></textarea>
          <label for="form-message">How we can help?</label>
        </div>

        <button type="submit" id="submit_btn" class="btn btn-info ml-0">Submit<i class="far fa-paper-plane ml-2"></i></button>
</form>
      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->


  </section>
  <!--Section: Content-->


</div>



{% endblock content %}

src/templates/forgot_pass.html
{% extends "base.html" %}
{% block title %}B&B{% endblock title %}
{% include "navbar.html" %}
{% block content %}

<div class="container" style="margin-top: 100px;">
<div class="row my-5">

<div class="col-12 text-center">
{% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
<div class="alert alert-danger text-center alter-dismissable fade show" role="alert">
{{ message }}
<button type="button" class="close" data-dismiss="alert">
  <span aria-hidden="true">&times;</span>
</button>
</div>
{% else %}
<div class="alert alert-success text-center alter-dismissable fade show" role="alert">
{{ message }}
<button type="button" class="close" data-dismiss="alert">
  <span aria-hidden="true">&times;</span>
</button>
</div>
{% endif %} {% endfor %} {% endif %} {% endwith %}
<h5 class="text-center my-2">Recover Password</h5>
<p>Please enter your email below, and we will send you a password reset link.</p>
</div>
<div class="col-12">
  <div class="modal-content mx-auto" style="width: 350px;">
    <!--Header-->
    
    <div class="modal-header mx-auto">
      <img src="{{ url_for('static', filename='img/pass_recovery.png') }}" class="img-responsive" style="width: 85px;">
    </div>
    <!--Body-->
    <div class="modal-body text-center mb-1">
<form action="{{ url_for('auth.reset_password') }}" method="POST">
      <div class="md-form ml-0 mr-0">
        <input type="email" name="email" class="form-control form-control-sm validate ml-0" id="email" required>
        <label data-error="wrong" data-success="right" for="email" class="ml-0">Your email address</label>
      </div>
      <div class="text-center mt-4">
        <button type="submit" class="btn btn-danger btn-rounded mt-1">Send Reset Email</button>
      </div>
</form>
    </div>
  </div>
</div>

</div>
</div>

{% endblock content %}

src/templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('views.home') }}"><strong>Bed &amp; Breakfast <i class="fas fa-utensils"></i></strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarMenu">
          <!--Links-->
          <ul class="navbar-nav ml-auto smooth-scroll">
{% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.home') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.rooms') }}">Rooms</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.contact') }}">Contact</a>
            </li>
{% if user.role == 0 %}
            <li class="nav-item avatar">
              <a class="nav-link p-0 ml-5" href="{{ url_for('views.user_dashboard') }}" title="Profile">
                <span class="yellow-text">Hi, </span>{{ user.fname }}
                <img src="{{ url_for('static', filename='img/user_avatars/') }}{{ user.avatar }}" class="rounded-circle z-depth-0" style="width: 40px; height: 40px;">
              </a>
            </li>
{% else %}
            <li class="nav-item avatar">
              <a class="nav-link p-0 ml-5" href="{{ url_for('views.admin_dashboard') }}" title="Profile">
                <span class="yellow-text">Hi, </span>{{ user.fname }}
                <img src="{{ url_for('static', filename='img/user_avatars/') }}{{ user.avatar }}" class="rounded-circle z-depth-0" style="width: 40px; height: 40px;">
              </a>
            </li>
{% endif %}
            <li class="nav-item ml-3 mt-2">
              <a class="text-white" title="Logout" data-toggle="modal" data-target="#user_logout">
                <i class="fas fa-sign-out-alt fa-lg"></i>
              </a>
            </li>
{% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.home') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.rooms') }}">Rooms</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.contact') }}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link btn btn-primary btn-sm" href="{{ url_for('auth.login') }}"><i class="fas fa-user"></i> Sign in</a>
            </li>
{% endif %}
          </ul>
        </div>
      </div>
</nav>

<div class="modal fade" id="user_logout" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body font-weight-bold text-center">Do you want to logout?</div>
      <div class="modal-footer d-inline">
        <button type="button" class="btn btn-danger btn-rounded btn-md w-25" data-dismiss="modal">No</button>
        <a href="{{ url_for('auth.logout') }}" class="btn btn-primary btn-rounded btn-md float-right w-25">Yes</a>
      </div>
    </div>
  </div>
</div>

src/templates/set_new_pass.html
{% extends "base.html" %}
{% block title %}B&B{% endblock title %}
{% include "navbar.html" %}
{% block content %}

<div class="container" style="margin-top: 100px;">
<div class="row my-5">

<div class="col-12 text-center">
{% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
<div class="alert alert-danger text-center alter-dismissable fade show" role="alert">
{{ message }}
<button type="button" class="close" data-dismiss="alert">
  <span aria-hidden="true">&times;</span>
</button>
</div>
{% else %}
<div class="alert alert-success text-center alter-dismissable fade show" role="alert">
{{ message }}
<button type="button" class="close" data-dismiss="alert">
  <span aria-hidden="true">&times;</span>
</button>
</div>
{% endif %} {% endfor %} {% endif %} {% endwith %}
<h5 class="text-center my-2 text-info font-weight-bold">Set New Password</h5>
<hr width="25px;">
</div>
<div class="col-12">
  <div class="modal-content mx-auto" style="width: 350px;">
    <!--Header-->
    
    <div class="modal-header mx-auto">
      <i class="fas fa-user-lock fa-4x"></i>
    </div>
    <!--Body-->
    <div class="modal-body mb-1">
<form action="{{ url_for('auth.set_new_pass') }}" method="POST">
      <div class="md-form ml-0 mr-0">
        <input type="password" name="password" id="password" class="form-control form-control-sm validate ml-0" required>
        <label for="password">New password</label>
      </div>
      <div class="md-form ml-0 mr-0">
        <input type="password" id="password2" class="form-control form-control-sm validate m-0" required>
        <label for="password2">Confirm password</label>
        <small id="match_res"></small>
      </div>
      <input type="hidden" name="user_id" value="{{ user_id }}">
      <div class="text-center mt-4">
        <button type="submit" id="set_new_pass_btn" class="btn btn-primary btn-rounded mt-1">Save</button>
      </div>
</form>
    </div>
  </div>
</div>

</div>
</div>

{% endblock content %}

src/templates/sign_up.html
{% extends "base.html" %}
{% block title %}B&B{% endblock title %}
{% include "navbar.html" %}
{% block content %}

<div class="container" style="margin-top: 100px;">
<div class="row my-5">
<div class="col-12">
{% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
<div class="alert alert-danger text-center alter-dismissable fade show" role="alert">
{{ message }}
<button type="button" class="close" data-dismiss="alert">
  <span aria-hidden="true">&times;</span>
</button>
</div>
{% else %}
<div class="alert alert-success text-center alter-dismissable fade show" role="alert">
{{ message }}
<button type="button" class="close" data-dismiss="alert">
  <span aria-hidden="true">&times;</span>
</button>
</div>
{% endif %} {% endfor %} {% endif %} {% endwith %}
</div>

<div class="card mx-auto">

    <h5 class="card-header info-color white-text text-center py-4">
        <strong>Sign up</strong>
    </h5>

    <!--Card content-->
    <div class="card-body px-lg-5 pt-0">

        <!-- Form -->
        <form class="text-center" style="color: #757575;" action="{{ url_for('auth.sign_up') }}" method="POST">

            <div class="form-row">
                <div class="col">
                    <!-- First name -->
                    <div class="md-form">
                        <input type="text" id="fname" name="fname" class="form-control" required>
                        <label for="fname">First name</label>
                    </div>
                </div>
                <div class="col">
                    <!-- Last name -->
                    <div class="md-form">
                        <input type="text" id="lname" name="lname" class="form-control" required>
                        <label for="lname">Last name</label>
                    </div>
                </div>
            </div>

            <!-- E-mail -->
            <div class="md-form mt-0">
                <input type="email" id="email" name="email" class="form-control" required>
                <label for="email">Email</label>
            </div>

            <!-- Password -->
            <div class="md-form">
                <input type="password" id="password1" name="password1" class="form-control" required>
                <label for="password1">Password</label>
            </div>
            <div class="md-form">
                <input type="password" id="password2" name="password2" class="form-control" required>
                <label for="password2">Confirm password</label>
            </div>

            <!-- Sign up button -->
            <button class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0" type="submit">Sign up</button>

            <hr>

            <!-- Terms of service -->
            <p>Already have an account? <a href="/login">Sign in</a>

        </form>
        <!-- Form -->

    </div>

</div>
<!-- Material form register -->

</div>
</div>

{% endblock content %}